import pygame as pg, math
from random import randint
from time import sleep

RAD_DEG_CONVERTER = 57.2958

GREY = (222, 222, 222)
RED = (255, 0, 0)
BLACK = (0, 0, 0)

W_WIDTH = 1080
W_HEIGHT = 720
W_PADDING = 20

C_SIDE_MAX = W_HEIGHT-(W_PADDING*2)
C_BORDER = 3

C_WIDTH = 8
C_HEIGHT = 8
C_CASE_LENGTH = C_SIDE_MAX//C_WIDTH if C_SIDE_MAX//C_WIDTH < C_SIDE_MAX//C_HEIGHT else C_SIDE_MAX//C_HEIGHT

C_SIDE_HEIGHT = C_HEIGHT * C_CASE_LENGTH
C_SIDE_WIDTH = C_WIDTH * C_CASE_LENGTH

C_LEFT = (W_WIDTH+400-(C_SIDE_WIDTH+W_PADDING))//2
C_TOP = (W_HEIGHT-(C_SIDE_HEIGHT))//2